export const glAccount = [
  {
    idGlAccount: 1,
    glAccount: 40010001,
    groupDetail: 'Expendable-Material',
    groupGl: 'Material Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 2,
    glAccount: 40012000,
    groupDetail: 'Repairable-Material',
    groupGl: 'Material Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 3,
    glAccount: 40020001,
    groupDetail: 'Rotable parts-Subcont',
    groupGl: 'Subcontract Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 4,
    glAccount: 40014200,
    groupDetail: 'Repairable parts-Subcont',
    groupGl: 'Subcontract Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 5,
    glAccount: 40000000,
    groupDetail: 'Base salary',
    groupGl: 'Staff Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 6,
    glAccount: 40002002,
    groupDetail: 'Honorarium',
    groupGl: 'Staff Expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 7,
    glAccount: 40000400,
    groupDetail: 'Travel',
    groupGl: 'Company accommodation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 8,
    glAccount: 40000403,
    groupDetail: 'Transport',
    groupGl: 'Company accommodation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 9,
    glAccount: 40030000,
    groupDetail: 'Rotable part',
    groupGl: 'Depreciation & amortisation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 10,
    glAccount: 40030001,
    groupDetail: 'Amortization',
    groupGl: 'Depreciation & amortisation',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 11,
    glAccount: 40040000,
    groupDetail: 'Maintenance and repair-Hangar',
    groupGl: 'Facility Maintenance expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 12,
    glAccount: 40040005,
    groupDetail: 'Maintenance and repair-Hardware',
    groupGl: 'Facility Maintenance expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
  {
    idGlAccount: 13,
    glAccount: 40041002,
    groupDetail: 'Building-Rental',
    groupGl: 'Rental expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 14,
    glAccount: 40041000,
    groupDetail: 'Component-Rental',
    groupGl: 'Rental expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 15,
    glAccount: 40043000,
    groupDetail: 'Electricity consumption',
    groupGl: 'Other operating expenses',
    sap: false,
    active: true,

    createdBy: '582127',
  },
  {
    idGlAccount: 16,
    glAccount: 40043006,
    groupDetail: 'Gas',
    groupGl: 'Other operating expenses',
    sap: false,
    active: true,
    createdBy: '582127',
  },
];

export const costCenters = [
  {
    costCenter: 'ZGMFTA',
    bidang: 'TA',
    dinas: 'TA',
    description: 'Post 1',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAF',
    bidang: 'TAF',
    dinas: 'TA',
    description: 'Post 2',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAR',
    bidang: 'TAR',
    dinas: 'TA',
    description: 'Post 3',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAX',
    bidang: 'TAX',
    dinas: 'TA',
    description: 'Post 4',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTD',
    bidang: 'TD',
    dinas: 'TD',
    description: 'Post 5',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDB',
    bidang: 'TDB',
    dinas: 'TD',
    description: 'Post 6',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDC',
    bidang: 'TDC',
    dinas: 'TD',
    description: 'Post 7',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDI',
    bidang: 'TDI',
    dinas: 'TD',
    description: 'Post 8',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDO',
    bidang: 'TDO',
    dinas: 'TD',
    description: 'Post 9',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTDS',
    bidang: 'TDS',
    dinas: 'TD',
    description: 'Post 10',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAP',
    bidang: 'TAP',
    dinas: 'TA',
    description: 'Post 11',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAB',
    bidang: 'TAB',
    dinas: 'TA',
    description: 'Post 12',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAG',
    bidang: 'TAG',
    dinas: 'TA',
    description: 'Post 13',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTAM',
    bidang: 'TAM',
    description: 'Post 14',
    dinas: 'TA',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTA',
    active: true,
    createdBy: '582127',
  },
  {
    costCenter: 'ZGMFTX',
    bidang: 'TX',
    description: 'Post 14',
    dinas: 'TX',
    directorat: 'DF',
    groupDinas: 'Supporting',
    profitCenter: 'ZGMFTX',
    active: true,
    createdBy: '582127',
  },
];

export const docCategory = [
  {
    module: 'OPEX',
    docCategory: 'HPS',
    description: 'Harga Perkiraan Sendiri',
    createdBy: '582127',
  },
  {
    module: 'OPEX',
    docCategory: 'PA',
    description: 'Profitability Analyst',
    createdBy: '582127',
  },
  {
    module: 'OPEX',
    docCategory: 'Other',
    description: 'Document pendukung lainnya',
    createdBy: '582127',
  },
];

export const status = [{}];
